# general settings
name: BasicVSR_64x7_LFN_Vimeo90K
# name: experiments
model_type: BasicVSRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KDataset
    # dataroot_gt: /root/proj/Datasets/REDS/sharp_data/train_sharp
    # dataroot_lq: /root/proj/Datasets/REDS/bicubic_data/train_sharp_bicubic/X4
    dataroot_gt: datasets/vimeo_septuplet/sequences/
    dataroot_lq: datasets/vimeo_septuplet/sequences_down/
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    # meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    io_backend:
      type: disk
    
    is_train : true
    num_frame: 7
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: true

  # val:
  #   name: REDS4
  #   type: REDSRecurrentDataset
  #   # dataroot_gt: /root/proj/Datasets/REDS/sharp_data/train_sharp    #val_sharp
  #   # dataroot_lq: /root/proj/Datasets/REDS/bicubic_data/train_sharp_bicubic/X4    #val_sharp_bicubic/X4
  #   dataroot_gt: datasets/REDS/train/train_sharp
  #   dataroot_lq: datasets/REDS/train/train_sharp_bicubic/X4
  #   meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
  #   val_partition: REDS4  # set to 'official' when use the official validation partition
  #   io_backend:
  #     type: disk

  #   is_val: true
  #   num_frame: 100
  #   gt_size: ~
  #   interval_list: [1]
  #   random_reverse: false
  #   use_flip: false
  #   use_rot: false


# network structures
network_g:
  type: BasicVSR
  num_feat: 64
  num_block: 7
  opticalflow_path: basicsr/models/archs/LiteFlowNet/models/liteflownet-sintel-final.pytorch

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [35000]
    # periods: [250000, 250000, 250000, 250000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 35000
  warmup_iter: -1  # no warm up
  fix_iter: 5000
  of_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# # validation settings
# val:
#   val_freq: !!float 5e3
#   # val_freq: !!float 2
#   save_img: true

#   metrics:
#     psnr: # metric name, can be arbitrary
#       type: calculate_psnr
#       crop_border: 0
#       test_y_channel: false

# logging settings
logger:
  print_freq: 100
  #print_freq: 1
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
